name: DynamicMarketplace
author: EnderGamingFilms
version: ${project.version}
main: me.endergaming.dynamicmarketplace.DynamicMarketplace
api-version: 1.13
depend: [Vault]
softdepend: [PlaceholderAPI]
permissions:
  market.reload:
    default: op
  market.command.buy:
    default: op
  market.command.sell:
    default: op
  market.command.sellall:
    default: op
  market.command.sellhand:
    default: op
  market.command.collector:
    default: op
  market.command.info:
    default: op
  market.command.worth:
    default: op
  market.command.*:
    default: op
    children:
      market.command.buy: true
      market.command.sell: true
      market.command.sellall: true
      market.command.sellhand: true
      market.command.collector: true
      market.command.info: true
      market.command.worth: true
  market.*:
    default: op
    children:
      market.command.*: true
      market.reload: true